### ISSUE TITLE
Cannot find module 'ink'

### ISSUE THREAD

**Issue by silvenon** [reactor-studio/terminal-cooker#1]
```
yarn global add terminal-cooker
cook --token=123
```
```
internal/modules/cjs/loader.js:615
    throw err;
    ^

Error: Cannot find module 'ink'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:613:15)
    at Function.Module._load (internal/modules/cjs/loader.js:539:25)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/silvenon/.config/yarn/global/node_modules/ink-select-input/dist/index.js:3:33)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
```

But the command works when cloning this repo and running `yarn link`.

**Comment by dinodsaurus** [comment]
woow thanks, I totally missed this :(
